import Link from "next/link";
export default function Page() {
  return (
    <div>
      <h1>Web dev 2 Demo</h1>
      <p>Generated by create next app</p>
      <li>
        <a href="/week-2">Week 2</a>
        <Link href="/week-2">Week 2 demos</Link>
      </li>
    </div>
  );
}